apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: n2mjn32yy-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/n2mjn32yy-java-springboot-gitops