apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n2mjn32yy-java-springboot
  janus-idp.io/tekton: n2mjn32yy-java-springboot
  backstage.io/kubernetes-id: n2mjn32yy-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n2mjn32yy-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
